
import React, { useState, useCallback, useEffect, useRef } from 'react';
import { 
  AppStep, 
  OutlineItem, 
  SlideContent, 
  ThemeConfig,
  GammaTheme,
  GammaFolder
} from './types';
import { THEMES, TONES, LANGUAGES } from './constants';
import { 
  generateOutline, 
  generateSlideFullContent, 
  generateImageForSlide,
  generatePresentationWithGamma,
  listGammaThemes,
  listGammaFolders
} from './services/geminiService';
import { Button } from './components/Button';
import { SlideRenderer } from './components/SlideRenderer';
import html2canvas from 'html2canvas';
import { jsPDF } from 'jspdf';
import pptxgen from 'pptxgenjs';

const App: React.FC = () => {
  const [step, setStep] = useState<AppStep>(AppStep.PROMPT);
  const [isLoading, setIsLoading] = useState(false);
  const [loadingMsg, setLoadingMsg] = useState('');
  const [exportProgress, setExportProgress] = useState<{current: number, total: number} | null>(null);
  
  // Presentation State
  const [topic, setTopic] = useState('');
  const [slideCount, setSlideCount] = useState(6);
  const [tone, setTone] = useState(TONES[0]);
  const [language, setLanguage] = useState(LANGUAGES[0]);
  const [outline, setOutline] = useState<OutlineItem[]>([]);
  const [slides, setSlides] = useState<SlideContent[]>([]);
  const [currentTheme, setCurrentTheme] = useState<ThemeConfig>(THEMES[0]);
  const [currentSlideIndex, setCurrentSlideIndex] = useState(0);
  
  // Custom Branding
  const [customLogo, setCustomLogo] = useState<string | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const exportContainerRef = useRef<HTMLDivElement>(null);

  // Gamma API State
  const [gammaThemes, setGammaThemes] = useState<GammaTheme[]>([]);
  const [gammaFolders, setGammaFolders] = useState<GammaFolder[]>([]);
  const [selectedGammaTheme, setSelectedGammaTheme] = useState<string>('');
  const [selectedGammaFolder, setSelectedGammaFolder] = useState<string>('');

  useEffect(() => {
    const fetchGammaData = async () => {
      const themes = await listGammaThemes();
      const folders = await listGammaFolders();
      setGammaThemes(themes);
      setGammaFolders(folders);
      if (themes.length > 0) {
        setSelectedGammaTheme(themes[0].id);
      }
    };
    fetchGammaData();
  }, []);

  const handleLogoUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onloadend = () => {
        setCustomLogo(reader.result as string);
      };
      reader.readAsDataURL(file);
    }
  };

  const removeLogo = () => {
    setCustomLogo(null);
    if (fileInputRef.current) fileInputRef.current.value = '';
  };

  const handleStartGeneration = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!topic.trim()) return;

    setIsLoading(true);
    setLoadingMsg('Analyzing topic and structuring content...');
    try {
      const result = await generateOutline(topic, slideCount, tone, language);
      setOutline(result);
      setStep(AppStep.OUTLINE);
    } catch (err) {
      alert('Failed to generate outline. Please try again.');
    } finally {
      setIsLoading(false);
    }
  };

  const handleGenerateSlides = async () => {
    setIsLoading(true);
    setLoadingMsg('Crafting detailed slides and visuals...');
    try {
      const slideData = await generateSlideFullContent(outline, tone, language);
      setSlides(slideData);
      setStep(AppStep.THEME);

      slideData.forEach(async (slide, idx) => {
        if (slide.imagePrompt) {
          try {
            const imgUrl = await generateImageForSlide(slide.imagePrompt);
            setSlides(prev => prev.map(s => s.id === slide.id ? { ...s, imageUrl: imgUrl } : s));
          } catch (e) {
            console.warn(`Failed to generate image for slide ${idx}`);
          }
        }
      });

    } catch (err) {
      alert('Failed to generate slide content.');
    } finally {
      setIsLoading(false);
    }
  };

  const handleGenerateWithGamma = async () => {
    if (!topic.trim()) {
      alert('Please enter a topic to generate a presentation with Gamma.');
      return;
    }
     if (!selectedGammaTheme) {
      alert('Please select a Gamma theme.');
      return;
    }
    setIsLoading(true);
    setLoadingMsg('Sending request to Gamma API...');
    try {
      const result = await generatePresentationWithGamma(
        topic, 
        Number(slideCount), 
        tone, 
        language,
        selectedGammaTheme,
        selectedGammaFolder
      );
      alert(`Success! Your presentation is being generated by Gamma. Generation ID: ${result.generationId}`);
    } catch (err) {
      console.error(err);
      alert(`Gamma API Error: ${err.message}`);
    } finally {
      setIsLoading(false);
    }
  };

  const handleExportPDF = async () => {
    if (!exportContainerRef.current) return;
    setIsLoading(true);
    setLoadingMsg('Exporting 1280x720 PDF...');
    setExportProgress({ current: 0, total: slides.length });

    try {
      const pdf = new jsPDF({
        orientation: 'landscape',
        unit: 'px',
        format: [1280, 720],
        hotfixes: ['px_scaling'],
      });

      const slideElements = exportContainerRef.current.children;
      
      for (let i = 0; i < slideElements.length; i++) {
        setExportProgress({ current: i + 1, total: slides.length });
        
        const canvas = await html2canvas(slideElements[i] as HTMLElement, {
          width: 1280, height: 720, scale: 2, useCORS: true,
          logging: false, backgroundColor: null, windowWidth: 1280, windowHeight: 720,
          onclone: (clonedDoc) => {
             const style = clonedDoc.createElement('style');
             style.innerHTML = "@import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700;900&display=swap'); body { font-family: 'Montserrat', sans-serif !important; }";
             clonedDoc.head.appendChild(style);
          }
        });
        
        const imgData = canvas.toDataURL('image/png', 1.0);
        if (i > 0) pdf.addPage([1280, 720], 'landscape');
        pdf.addImage(imgData, 'PNG', 0, 0, 1280, 720, undefined, 'FAST');
      }

      pdf.save(`${topic.replace(/\s+/g, '_')}_1280x720.pdf`);
    } catch (err) {
      console.error(err);
      alert('Failed to export PDF.');
    } finally {
      setIsLoading(false);
      setExportProgress(null);
    }
  };

  const handleExportPPTX = async () => {
    setIsLoading(true);
    setLoadingMsg('Generating professional PPTX...');
    
    try {
      const pres = new pptxgen();
      // Set layout to 16:9 HD (1280x720 pixels)
      pres.layout = { name: '16x9', width: 13.33, height: 7.5 };
      pres.title = topic;
      
      const isFearless = currentTheme.id === 'fearless';
      const bgHex = isFearless ? '5C3977' : 'FAF7F2';
      const textHex = isFearless ? 'FFFFFF' : '2C1810';
      const accentHex = 'EE5340';
      const font = 'Montserrat';

      slides.forEach((slide) => {
        const pSlide = pres.addSlide();
        pSlide.background = { fill: bgHex };

        if (customLogo && slide.type !== 'title' && slide.type !== 'closing') {
          pSlide.addImage({ data: customLogo, x: '88%', y: '85%', w: '10%', h: '10%', sizing: { type: 'contain' } });
        }

        switch(slide.type) {
          case 'title':
            if (customLogo) pSlide.addImage({ data: customLogo, x: '8%', y: '15%', w: '15%', h: '15%', sizing: { type: 'contain' } });
            pSlide.addText(slide.title, { x: '8%', y: '35%', w: '84%', h: '35%', fontSize: 54, bold: true, color: textHex, fontFace: font, align: 'left', valign: 'top' });
            pSlide.addText(slide.points[0] || '', { x: '8%', y: '70%', w: '84%', h: '10%', fontSize: 24, color: textHex, fontFace: font, opacity: 60 });
            break;
          case 'agenda': case 'content':
            pSlide.addText(slide.title, { x: '5%', y: '8%', w: '90%', fontSize: 36, bold: true, color: accentHex, fontFace: font, transform: { uppercase: true } });
            pSlide.addText(slide.points.join('\n\n'), { x: '5%', y: '25%', w: '45%', h: '65%', fontSize: 20, color: textHex, bullet: true, fontFace: font, valign: 'top', lineSpacing: 28 });
            if (slide.imageUrl) pSlide.addImage({ data: slide.imageUrl, x: '55%', y: '22%', w: '40%', h: '68%', sizing: { type: 'cover' } });
            break;
          case 'split':
            pSlide.addShape(pres.ShapeType.rect, { x: 0, y: 0, w: '50%', h: '100%', fill: { color: isFearless ? '5C3977' : 'F0ECE4' } });
            pSlide.addShape(pres.ShapeType.rect, { x: '50%', y: 0, w: '50%', h: '100%', fill: { color: isFearless ? 'FFFFFF' : 'FAF7F2' } });
            pSlide.addText(slide.title, { x: '5%', y: '25%', w: '40%', h: '50%', fontSize: 42, bold: true, color: isFearless ? 'FFFFFF' : textHex, fontFace: font, valign: 'middle' });
            pSlide.addText(slide.points.join('\n'), { x: '55%', y: '25%', w: '40%', h: '50%', fontSize: 22, color: textHex, fontFace: font, bullet: true, valign: 'middle' });
            break;
          case 'quote':
            pSlide.addText('“', { x: 0, y: '15%', w: '100%', fontSize: 140, align: 'center', color: accentHex, opacity: 20 });
            pSlide.addText(slide.title, { x: '10%', y: '22%', w: '80%', h: '50%', fontSize: 36, italic: true, color: textHex, align: 'center', fontFace: font, valign: 'middle' });
            pSlide.addText(`— ${slide.points[0] || ''}`, { x: '10%', y: '75%', w: '80%', fontSize: 24, bold: true, color: textHex, align: 'center', fontFace: font, opacity: 60 });
            break;
          case 'highlight':
            pSlide.addShape(pres.ShapeType.rect, { x: '10%', y: '35%', w: '80%', h: '30%', fill: { color: 'FFFFFF' } });
            pSlide.addText(slide.title, { x: '10%', y: '35%', w: '80%', h: '30%', fontSize: 48, bold: true, color: '5C3977', align: 'center', fontFace: font, valign: 'middle' });
            break;
          case 'section':
            pSlide.addText(slide.title, { x: '5%', y: '25%', w: '40%', h: '50%', fontSize: 64, bold: true, color: 'FFFFFF', fontFace: font, valign: 'middle' });
            pSlide.addText(slide.points[0] || '', { x: '50%', y: '25%', w: '45%', h: '50%', fontSize: 24, color: 'FFFFFF', fontFace: font, opacity: 60, valign: 'middle' });
            break;
          case 'closing':
            if (customLogo) pSlide.addImage({ data: customLogo, x: '35%', y: '25%', w: '30%', h: '35%', sizing: { type: 'contain' } });
            pSlide.addText('Thank You', { x: 0, y: '68%', w: '100%', fontSize: 42, bold: true, color: 'FFFFFF', align: 'center', fontFace: font });
            pSlide.addText('For Your Attention', { x: 0, y: '78%', w: '100%', fontSize: 18, color: 'FFFFFF', align: 'center', fontFace: font, opacity: 40, transform: { uppercase: true } });
            break;
          case 'image':
            if (slide.imageUrl) pSlide.addImage({ data: slide.imageUrl, x: 0, y: 0, w: '100%', h: '100%', sizing: { type: 'cover' } });
            pSlide.addShape(pres.ShapeType.rect, { x: 0, y: '70%', w: '100%', h: '30%', fill: { color: '000000', opacity: 60 } });
            pSlide.addText(slide.title, { x: '5%', y: '75%', w: '90%', fontSize: 48, bold: true, color: 'FFFFFF', fontFace: font });
            break;
        }
      });

      pres.writeFile({ fileName: `${topic.replace(/\s+/g, '_')}.pptx` });
    } catch (err) {
      console.error(err);
      alert('Failed to export PPTX.');
    } finally {
      setIsLoading(false);
    }
  };

  const handleNextSlide = () => setCurrentSlideIndex(i => Math.min(i + 1, slides.length - 1));
  const handlePrevSlide = () => setCurrentSlideIndex(i => Math.max(i - 1, 0));

  const renderLoading = () => (
    <div className="fixed inset-0 bg-white/90 backdrop-blur-xl z-[100] flex flex-col items-center justify-center space-y-6">
      <div className="relative">
        <div className="w-24 h-24 border-4 border-indigo-100 border-t-indigo-600 rounded-full animate-spin"></div>
        <div className="absolute inset-0 flex items-center justify-center"><div className="w-10 h-10 bg-indigo-600 rounded-xl animate-pulse shadow-xl"></div></div>
      </div>
      <div className="text-center space-y-3">
        <h3 className="text-2xl font-bold text-slate-800 tracking-tight">{loadingMsg}</h3>
        {exportProgress && (
          <div className="w-64 h-2 bg-slate-100 rounded-full overflow-hidden mx-auto border border-slate-200">
            <div className="h-full bg-indigo-600 transition-all duration-300" style={{ width: `${(exportProgress.current / exportProgress.total) * 100}%` }}></div>
            <p className="text-xs font-bold text-slate-400 mt-4 uppercase tracking-widest">Processing Slide {exportProgress.current} of {exportProgress.total}</p>
          </div>
        )}
      </div>
    </div>
  );

  return (
    <div className="min-h-screen flex flex-col font-sans bg-[#F8FAFC]">
      {isLoading && renderLoading()}
      <header className="sticky top-0 z-40 bg-white/80 backdrop-blur-md border-b border-slate-200">
        <div className="max-w-7xl mx-auto px-4 h-16 flex items-center justify-between">
          <div className="flex items-center space-x-2 cursor-pointer group" onClick={() => setStep(AppStep.PROMPT)}>
            <div className="w-9 h-9 bg-indigo-600 rounded-xl flex items-center justify-center text-white font-black shadow-lg shadow-indigo-200 transform group-hover:rotate-12 transition-transform">P</div>
            <span className="text-xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-indigo-600 to-purple-600 tracking-tight">Presenton AI</span>
          </div>
          <div className="hidden md:flex items-center space-x-6">
            <div className={`h-1 w-10 rounded-full transition-all duration-500 ${step === AppStep.PROMPT ? 'bg-indigo-600 w-16' : 'bg-slate-200'}`}></div>
            <div className={`h-1 w-10 rounded-full transition-all duration-500 ${step === AppStep.OUTLINE ? 'bg-indigo-600 w-16' : 'bg-slate-200'}`}></div>
            <div className={`h-1 w-10 rounded-full transition-all duration-500 ${step === AppStep.THEME ? 'bg-indigo-600 w-16' : 'bg-slate-200'}`}></div>
            <div className={`h-1 w-10 rounded-full transition-all duration-500 ${step === AppStep.VIEWER ? 'bg-indigo-600 w-16' : 'bg-slate-200'}`}></div>
          </div>
          <div className="flex items-center space-x-3">
            {step === AppStep.VIEWER && (
              <div className="flex space-x-2">
                <Button variant="outline" onClick={handleExportPDF} className="bg-white">PDF</Button>
                <Button variant="outline" onClick={handleExportPPTX} className="bg-white">PPTX</Button>
              </div>
            )}
          </div>
        </div>
      </header>

      <main className="flex-1 max-w-7xl mx-auto w-full px-4 py-8">
        {step === AppStep.PROMPT && (
          <div className="max-w-3xl mx-auto py-12 space-y-12 animate-in fade-in slide-in-from-bottom-8 duration-700">
            <div className="text-center space-y-4">
              <h1 className="text-5xl md:text-7xl font-display font-bold text-slate-900 leading-[1.1] tracking-tighter">Visual Stories <span className="text-indigo-600 italic underline decoration-indigo-200 underline-offset-8">Perfected</span></h1>
              <p className="text-xl text-slate-500 max-w-2xl mx-auto font-medium">Transform any idea into a boardroom-ready presentation with the power of Gemini 3.</p>
            </div>
            <form onSubmit={handleStartGeneration} className="bg-white p-10 rounded-[32px] shadow-2xl shadow-indigo-100/50 border border-slate-100 space-y-10">
              <div className="space-y-3">
                <label className="text-sm font-bold text-slate-400 uppercase tracking-widest ml-1">What is your topic?</label>
                <input type="text" value={topic} onChange={(e) => setTopic(e.target.value)} placeholder="e.g. Modern Architecture Trends 2025" className="w-full px-8 py-5 rounded-2xl border-2 border-slate-100 focus:border-indigo-500 focus:ring-0 text-xl font-medium transition-all shadow-sm" required />
              </div>
              <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                {[ { label: 'Length', state: slideCount, setter: setSlideCount, options: [4, 6, 8, 10, 12], suffix: ' Slides' }, { label: 'Tone', state: tone, setter: setTone, options: TONES }, { label: 'Language', state: language, setter: setLanguage, options: LANGUAGES } ].map((conf, i) => (
                  <div key={i} className="space-y-3">
                    <label className="text-xs font-bold text-slate-400 uppercase tracking-widest ml-1">{conf.label}</label>
                    <select value={conf.state} onChange={(e) => conf.setter(e.target.value as any)} className="w-full px-5 py-4 rounded-2xl border-2 border-slate-100 focus:border-indigo-500 bg-white font-bold text-slate-700 shadow-sm transition-all">
                      {conf.options.map((opt: any) => (<option key={opt} value={opt}>{opt}{conf.suffix || ''}</option>))}
                    </select>
                  </div>
                ))}
              </div>
              <Button type="submit" className="w-full py-6 text-xl rounded-2xl" isLoading={isLoading}>
                Generate Outline
              </Button>
            </form>
          </div>
        )}
        {step === AppStep.OUTLINE && (
          <div className="max-w-4xl mx-auto space-y-10 animate-in fade-in duration-500">
            <div className="text-center">
              <h2 className="text-4xl font-black text-slate-900 tracking-tight">Review Structure</h2>
              <p className="text-lg text-slate-500 font-medium mt-2">Fine-tune the flow, then choose your generation engine.</p>
            </div>

            <div className="space-y-4">
              {outline.map((item, idx) => (
                <div key={item.id} className="group bg-white p-8 rounded-[24px] border border-slate-100 shadow-sm hover:shadow-xl hover:scale-[1.01] transition-all flex items-start space-x-8">
                  <div className="w-12 h-12 rounded-2xl bg-slate-900 flex items-center justify-center text-white font-mono text-lg shrink-0 shadow-lg">{idx + 1}</div>
                  <div className="flex-1 space-y-4">
                    <div className="flex items-center justify-between gap-4">
                      <input 
                        className="font-bold text-2xl text-slate-800 bg-transparent border-none p-2 focus:ring-2 focus:ring-indigo-200 focus:rounded-lg w-full tracking-tight transition-all" 
                        value={item.title} 
                        onChange={(e) => { const newOutline = [...outline]; newOutline[idx].title = e.target.value; setOutline(newOutline); }} 
                      />
                      <span className="text-[10px] font-black uppercase tracking-[0.2em] text-indigo-600 bg-indigo-50 px-3 py-1.5 rounded-lg border border-indigo-100 shrink-0">{item.slideType}</span>
                    </div>
                    <textarea 
                      className="text-slate-600 w-full bg-slate-50 rounded-lg p-4 border-2 border-slate-100 focus:ring-2 focus:ring-indigo-200 focus:border-indigo-200 text-base font-medium resize-none transition-colors" 
                      rows={3} 
                      value={item.description} 
                      onChange={(e) => { const newOutline = [...outline]; newOutline[idx].description = e.target.value; setOutline(newOutline); }} 
                    />
                  </div>
                </div>
              ))}
            </div>
            
            <div className="pt-8 border-t border-slate-200 grid grid-cols-1 md:grid-cols-2 gap-8 items-start">
                <div className="bg-white p-8 rounded-2xl border border-slate-200 shadow-sm flex flex-col items-center text-center space-y-6">
                    <h3 className="text-2xl font-bold text-slate-800">Continue with Presenton AI</h3>
                    <p className="text-slate-500">Use our internal engine to craft each slide with detailed content and custom-generated images.</p>
                    <Button onClick={handleGenerateSlides} className="px-8 py-4 text-lg w-full" isLoading={isLoading && loadingMsg.includes('visuals')}>
                      Craft Slides
                    </Button>
                </div>

                <div className="bg-white p-8 rounded-2xl border border-slate-200 shadow-sm flex flex-col text-center space-y-6">
                    <h3 className="text-2xl font-bold text-slate-800">Generate with Gamma</h3>
                    <p className="text-slate-500">Send your topic directly to the Gamma API using your workspace themes and folders.</p>
                    <div className="space-y-4 w-full text-left">
                      <div className="space-y-2">
                          <label className="text-xs font-bold text-slate-400 uppercase tracking-widest ml-1">Gamma Theme</label>
                          <select value={selectedGammaTheme} onChange={(e) => setSelectedGammaTheme(e.target.value)} className="w-full px-5 py-3 rounded-xl border-2 border-slate-200 focus:border-indigo-500 bg-white font-bold text-slate-700 shadow-sm transition-all">
                            {gammaThemes.map(theme => (<option key={theme.id} value={theme.id}>{theme.name} ({theme.type})</option>))}
                          </select>
                      </div>
                      <div className="space-y-2">
                          <label className="text-xs font-bold text-slate-400 uppercase tracking-widest ml-1">Save to Folder (Optional)</label>
                          <select value={selectedGammaFolder} onChange={(e) => setSelectedGammaFolder(e.target.value)} className="w-full px-5 py-3 rounded-xl border-2 border-slate-200 focus:border-indigo-500 bg-white font-bold text-slate-700 shadow-sm transition-all">
                            <option value="">Workspace Root</option>
                            {gammaFolders.map(folder => (<option key={folder.id} value={folder.id}>{folder.name}</option>))}
                          </select>
                      </div>
                    </div>
                    <Button onClick={handleGenerateWithGamma} variant="secondary" className="px-8 py-4 text-lg w-full" isLoading={isLoading && loadingMsg.includes('Gamma')}>
                      Generate with Gamma
                    </Button>
                </div>
            </div>
          </div>
        )}
        {step === AppStep.THEME && (
          <div className="space-y-12 animate-in fade-in duration-700">
            <div className="text-center space-y-4">
              <h2 className="text-5xl font-black text-slate-900 tracking-tight">Visual Identity</h2>
              <p className="text-xl text-slate-500 font-medium">Select a theme and add your branding.</p>
            </div>
            <div className="max-w-3xl mx-auto space-y-8">
              <div className="bg-white p-8 rounded-3xl border border-slate-100 space-y-6 shadow-xl shadow-indigo-100/50">
                <div className="flex items-center justify-between">
                  <div className="space-y-1">
                    <h4 className="font-bold text-slate-800 text-lg">Custom Branding</h4>
                    <p className="text-sm text-slate-500 font-medium">Elevate your deck with your professional logo.</p>
                  </div>
                  {!customLogo ? (<Button type="button" variant="outline" onClick={() => fileInputRef.current?.click()} className="bg-white shadow-sm">Upload Logo</Button>) : (<Button type="button" variant="ghost" onClick={removeLogo} className="text-red-500 hover:bg-red-50">Remove</Button>)}
                  <input type="file" ref={fileInputRef} className="hidden" accept="image/*" onChange={handleLogoUpload} />
                </div>
                {customLogo && (
                  <div className="flex items-center space-x-6 p-4 bg-white rounded-2xl border border-slate-100 animate-in zoom-in-95 duration-300">
                    <div className="w-20 h-20 bg-slate-50 rounded-xl border border-slate-200 p-3 shadow-inner flex items-center justify-center"><img src={customLogo} alt="Preview" className="max-w-full max-h-full object-contain" /></div>
                    <div className="space-y-1"><p className="text-sm font-bold text-slate-700">Logo detected</p><p className="text-xs text-slate-400 font-medium italic">Will be integrated into all slide layouts.</p></div>
                  </div>
                )}
              </div>
            </div>
            <div className="flex items-center justify-center gap-10">
              {THEMES.map(theme => (
                <div key={theme.id} onClick={() => setCurrentTheme(theme)} className={`cursor-pointer group relative overflow-hidden rounded-[32px] border-4 transition-all duration-500 w-full max-w-lg ${currentTheme.id === theme.id ? 'border-indigo-600 scale-[1.05] shadow-2xl' : 'border-transparent shadow-lg'}`}>
                  <div className={`aspect-video ${theme.styles.background} p-10 flex flex-col justify-between`}>
                    <h3 className={`${theme.styles.titleFont} ${theme.styles.text} text-3xl`}>{theme.name}</h3>
                    <div className="flex space-x-3"><div className={`w-12 h-3 rounded-full ${theme.styles.accent} bg-current`}></div><div className={`w-16 h-3 rounded-full ${theme.styles.accent} bg-current opacity-30`}></div></div>
                  </div>
                  <div className="bg-white p-6 flex justify-between items-center border-t border-slate-50">
                    <span className="font-bold text-slate-800 text-lg uppercase tracking-widest">{theme.name}</span>
                    <div className="w-8 h-8 rounded-full border border-slate-200" style={{ backgroundColor: theme.previewColor }}></div>
                  </div>
                </div>
              ))}
            </div>
            <div className="flex justify-center pt-8"><Button className="px-16 py-6 text-2xl rounded-2xl shadow-2xl shadow-indigo-200" onClick={() => setStep(AppStep.VIEWER)}>Generate Presentation</Button></div>
          </div>
        )}
        {step === AppStep.VIEWER && (
          <div className="flex flex-col h-full space-y-10 animate-in fade-in duration-500">
            <div className="flex justify-between items-center bg-white p-6 rounded-[24px] shadow-sm border border-slate-100">
              <div className="flex items-center space-x-6">
                <Button variant="ghost" onClick={() => setStep(AppStep.THEME)} className="font-bold uppercase tracking-widest text-xs">Switch Theme</Button>
                <div className="h-8 w-px bg-slate-200"></div>
                <div className="flex flex-col"><span className="text-[10px] font-black uppercase tracking-[0.3em] text-slate-300">Viewing Slide</span><span className="text-xl font-black text-indigo-600">{currentSlideIndex + 1} <span className="text-slate-200">/</span> {slides.length}</span></div>
              </div>
              <div className="flex items-center space-x-4">
                <Button variant="outline" onClick={handlePrevSlide} disabled={currentSlideIndex === 0} className="bg-white rounded-xl">Prev</Button>
                <Button variant="outline" onClick={handleNextSlide} disabled={currentSlideIndex === slides.length - 1} className="bg-white rounded-xl">Next</Button>
              </div>
            </div>
            <div className="flex-1 flex items-center justify-center group/view">
               {slides.length > 0 && (<div className="w-full max-w-[1200px] shadow-[0_40px_100px_rgba(0,0,0,0.2)] rounded-[20px] overflow-hidden transform transition-transform duration-700 group-hover/view:scale-[1.01]"><SlideRenderer slide={slides[currentSlideIndex]} theme={currentTheme} isActive={true} customLogoUrl={customLogo}/></div>)}
            </div>
            <div className="grid grid-cols-4 md:grid-cols-6 lg:grid-cols-10 gap-6 overflow-x-auto py-8 px-2 scrollbar-hide">
              {slides.map((slide, idx) => (
                <div key={slide.id} onClick={() => setCurrentSlideIndex(idx)} className={`cursor-pointer transition-all duration-300 ${currentSlideIndex === idx ? 'ring-4 ring-indigo-500 scale-110 shadow-xl' : 'opacity-40 hover:opacity-100 hover:scale-105'}`}>
                  <div className={`aspect-video w-full rounded-xl overflow-hidden ${currentTheme.styles.background} border border-slate-200 flex items-center justify-center p-3 relative`}>
                    <div className="text-[4px] leading-tight overflow-hidden text-center scale-[0.6]"><h4 className={`${currentTheme.styles.text} font-bold`}>{slide.title}</h4></div>
                    {slide.imageUrl && <div className="absolute inset-0 bg-white/5 pointer-events-none"></div>}
                  </div>
                  <div className={`text-center text-[10px] mt-2 font-black transition-colors ${currentSlideIndex === idx ? 'text-indigo-600' : 'text-slate-300'}`}>0{idx + 1}</div>
                </div>
              ))}
            </div>
            <div id="print-container" ref={exportContainerRef} className="fixed left-[-9999px] top-[-9999px]">
               {slides.map((slide, idx) => (<div key={slide.id} className="slide-page" style={{ width: '1280px', height: '720px', position: 'relative', overflow: 'hidden' }}><SlideRenderer slide={slide} theme={currentTheme} isActive={true} customLogoUrl={customLogo}/></div>))}
            </div>
          </div>
        )}
      </main>
      <footer className="py-12 border-t border-slate-100 bg-white">
        <div className="max-w-7xl mx-auto px-4 text-center space-y-4">
          <div className="flex items-center justify-center space-x-6">
            <p className="text-xs font-black text-slate-300 tracking-[0.4em] uppercase">Built with Gemini 3</p>
            <div className="w-1.5 h-1.5 rounded-full bg-slate-200"></div>
            <p className="text-xs font-black text-slate-300 tracking-[0.4em] uppercase">Enterprise Design Engine</p>
          </div>
          <p className="text-[10px] text-slate-400 font-bold uppercase tracking-widest opacity-50">&copy; 2025 Presenton Labs • All Rights Reserved</p>
        </div>
      </footer>
    </div>
  );
};

export default App;
